include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    kconfig: |
      CONFIG_ZMK_STUDIO=y
      CONFIG_ZMK_STUDIO_USB=y
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: seeeduino_xiao_ble
    shield: settings_reset
