include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    snippet: studio-rpc-usb-uart
    kconfig: |
      CONFIG_ZMK_STUDIO=y
  - board: seeeduino_xiao_ble
    shield: totem_right
    snippet: studio-rpc-usb-uart
    kconfig: |
      CONFIG_ZMK_STUDIO=y
