include:
  - board: seeeduino_xiao_ble
    shield: totem_left
    snippets:
      - studio-rpc-usb-uart
    cmake-args: "-DCONFIG_ZMK_STUDIO=y"
  - board: seeeduino_xiao_ble
    shield: totem_right
  - board: seeeduino_xiao_ble
    shield: settings_reset
